# **Numpy: Package for Multidimensional Array**

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)

In [4]:
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [7]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [10]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.random.rand()

0.8433853491447412

In [19]:
np.random.rand(3,2)

array([[0.75997219, 0.37446801],
       [0.91737745, 0.70940595],
       [0.23706788, 0.68315431]])

In [20]:
np.random.randn(3,2)

array([[ 0.83027965,  0.58091012],
       [-2.17369896, -1.37548414],
       [ 0.46534792, -0.47307234]])

In [21]:
np.random.ranint(1,5)

AttributeError: ignored

In [22]:
np.random.randint(1,5)

1

In [23]:
np.random.randint(34,100,50)

array([84, 77, 59, 56, 44, 98, 40, 71, 63, 76, 48, 43, 74, 54, 91, 50, 87,
       56, 88, 75, 98, 36, 65, 36, 97, 51, 52, 77, 94, 97, 98, 50, 53, 86,
       60, 94, 38, 89, 50, 70, 67, 52, 83, 83, 88, 59, 71, 86, 77, 78])

In [24]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
rand_array=np.random.randint(0,100,20)
rand_array

array([52, 36, 39, 66, 18, 59, 43, 76, 74, 69, 30, 53,  8,  6, 26,  1,  7,
       56, 93,  1])

In [26]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [27]:
rand_array.min()

1

In [28]:
rand_array.argmin()

15

In [29]:
rand_array.argmin(36)

AxisError: ignored

In [30]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
sample_array[3]

13

In [34]:
sample_array[3:7]

array([13, 14, 15, 16])

In [35]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [36]:
sample_array=np.arange(10,21)

In [37]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
sample_array(:)

SyntaxError: ignored

In [39]:
sample_array(0:7)

SyntaxError: ignored

In [40]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [41]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [42]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [43]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# **Two Dimensional Array**

In [52]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [46]:
sample_matrix[:,3]

array([23, 33,  7])

In [47]:
sample_matrix[0:2,2]

array([ 1, 21])

In [48]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [49]:
sample_matrix[2]

array([56, 76, 24,  7])

In [50]:
sample[:,(3,2)]

NameError: ignored

In [51]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [53]:
sample_array=np.arange(1,20)

In [54]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [55]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [56]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [57]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [58]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [59]:
np.max(sample_array)

19

In [60]:
np.min(sample_array)

1

In [61]:
np.argmin(sample_array)

0

In [62]:
np.argmax(sample_array)

18

In [63]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [64]:
np.std(sample_array)

5.477225575051661

In [65]:
np.var(sample_array)

30.0

In [66]:
np.mean(sample_array)

10.0

In [67]:
array=np.random.randn(3,4)
array

array([[ 1.28187282, -1.49880206, -0.42364927, -1.34549285],
       [ 0.16264027, -1.09725362, -0.61605706,  0.10590425],
       [ 0.17062508,  1.35686362,  1.020247  ,  2.02037524]])

In [68]:
np.round(array,decimals=3)

array([[ 1.282, -1.499, -0.424, -1.345],
       [ 0.163, -1.097, -0.616,  0.106],
       [ 0.171,  1.357,  1.02 ,  2.02 ]])

In [70]:
sports=np.array(['golf','cricket','fball','cricket','fball','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')